CREATE TABLE messages (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL,
    name TEXT NOT NULL,
    content TEXT NOT NULL,
    reply_to INTEGER,
    visible INTEGER DEFAULT 1 NOT NULL,
    verified INTEGER DEFAULT 0 NOT NULL,
    site TEXT
  );
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE ntfy (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    date TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL,
    text TEXT NOT NULL
  );
